### ISSUE TITLE
port the src of graphql-js

### ISSUE THREAD

**Issue by kfly8** [kfly8/GraphQL-Tiny#1]
This issue is porting the src directory of graphql-js.
https://github.com/graphql/graphql-js/tree/main/src

## How to work

If you have a file you want to port, write the name beside the file.

Please write tests as well as porting. Of course, the tests written in graphql-js should be ported, and in addition to that, please aim for 100% C0 coverage to improve the quality of the code.

## TODO

- language/
  - [x] ast.ts @kfly8
  - [x] blockString.ts @kfly8
    - [ ] port(test): blockString-fuzz (after lexer ported)
  - [x] characterClasses.ts @kfly8 
  - [ ] directiveLocation.ts
  - [ ] index.ts
  - [x] kinds.ts @kfly8
  - [ ] lexer.ts @AnaTofuZ 
  - [x] location.ts @kfly8
  - [ ] parser.ts
  - [ ] predicates.ts
  - [x] printer.ts @kfly8
  - [ ] printLocation.ts
  - [x] printString.ts @kfly8 
  - [ ] README.md
  - [x] source.ts @kfly8
  - [x] tokenKind.ts @kfly8
  - [ ] visitor.ts @kfly8
- error/
  - [x] GraphQLError.ts @kfly8 
    - [ ] port(test): GraphQLError @kfly8 (after parser ported)
  - [x] README.md @kfly8
  - [x] index.ts @kfly8 
  - [x] locatedError.ts @kfly8
  - [x] syntaxError.ts @kfly8
- execution/
  - [ ] README.md
  - [ ] collectFields.ts
  - [ ] execute.ts @kfly8
  - [ ] index.ts
  - [ ] mapAsyncIterable.ts
  - [ ] values.ts
- type/
  - [ ] README.md
  - [x] assertName.ts @kfly8 
  - [ ] (wip) definition.ts @kfly8 
  - [ ] directives.ts @kfly8 
  - [ ] index.ts @kfly8 
  - [ ] introspection.ts @kfly8 
  - [ ] scalars.ts @kfly8 
  - [ ] schema.ts @kfly8 
  - [ ] validate.ts @kfly8 
- utilities/
  - [ ] README.md
  - [ ] TypeInfo.ts
  - [ ] astFromValue.ts
  - [ ] buildASTSchema.ts
  - [ ] buildClientSchema.ts
  - [ ] coerceInputValue.ts
  - [ ] concatAST.ts
  - [ ] extendSchema.ts
  - [ ] findBreakingChanges.ts
  - [ ] getIntrospectionQuery.ts
  - [ ] getOperationAST.ts
  - [ ] index.ts
  - [ ] introspectionFromSchema.ts
  - [ ] lexicographicSortSchema.ts
  - [ ] printSchema.ts
  - [ ] separateOperations.ts
  - [ ] sortValueNode.ts
  - [ ] stripIgnoredCharacters.ts
  - [ ] typeComparators.ts
  - [ ] typeFromAST.ts
  - [ ] typedQueryDocumentNode.ts
  - [ ] valueFromAST.ts
  - [ ] valueFromASTUntyped.ts
- validation/
  - [ ]  rules/
  - [ ] README.md
  - [ ] ValidationContext.ts
  - [ ] index.ts
  - [ ] specifiedRules.ts
  - [ ] validate.ts
- jsutils/
  - NOTE: port if necessary
- [ ] graphql.ts
- [ ] index.ts
- [ ] version.ts
